### ISSUE TITLE
Child task does not display custom icons when in Live Preview

### ISSUE THREAD

**Issue by orionp** [replete/obsidian-tasks-custom-icons#1]
Given a parent and child task, such as:

```
- [ ] Parent ⏫ 🔁 every day ➕ 2023-05-17 🛫 2023-05-17 ⏳ 2023-05-18 📅 2023-05-19
	- [ ] Child ⏫ 🔁 every day ➕ 2023-05-17 🛫 2023-05-17 ⏳ 2023-05-18 📅 2023-05-19
```

The parent task will show replacement emoji, but the child will not:

<img width="743" alt="image" src="https://github.com/replete/obsidian-tasks-custom-icons/assets/128878/97a1db85-83bc-44dc-99dd-05d6f1c01b2f">

This also occurs if the parent is a bullet point, rather than a task.

Occurs with Default theme (though screenshot is from Minimal), and with all 4 CSS variants currently available.

**Comment by replete** [comment]
Oops, I forgot to fix this. Pushed a fix.

![Screenshot 2023-05-17 at 23 08 46](https://github.com/replete/obsidian-tasks-custom-icons/assets/812139/8d7f07e9-3aa6-4679-9338-d4286d66fbe2)

This selector
```css
.cm-line:has(.task-list-label) .cm-list-1 {}
```

needed to be:
```css
.cm-line:has(.task-list-label) [class^=cm-list-] {}
```

This should fix it for all levels.

**Comment by orionp** [comment]
Rock solid experience, now… thank you!
